// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjdT2RFDlKLhFrQlB2puqTmdb5ni0H3Uo',
    appId: '1:791187601680:web:250df941f02b79b96c4d95',
    messagingSenderId: '791187601680',
    projectId: 'gauri-lab8-bf36b',
    authDomain: 'gauri-lab8-bf36b.firebaseapp.com',
    storageBucket: 'gauri-lab8-bf36b.firebasestorage.app',
    measurementId: 'G-QN3K8QKNGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFiV_6CedetEIFZsY3QSvJc3UsmFgzo1g',
    appId: '1:791187601680:android:6e243c6693241aec6c4d95',
    messagingSenderId: '791187601680',
    projectId: 'gauri-lab8-bf36b',
    storageBucket: 'gauri-lab8-bf36b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzG3TEockSdW1AO4Nn_2o7P1Zz2jEILqw',
    appId: '1:791187601680:ios:00cfd708d6a72add6c4d95',
    messagingSenderId: '791187601680',
    projectId: 'gauri-lab8-bf36b',
    storageBucket: 'gauri-lab8-bf36b.firebasestorage.app',
    iosBundleId: 'com.example.lab8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzG3TEockSdW1AO4Nn_2o7P1Zz2jEILqw',
    appId: '1:791187601680:ios:00cfd708d6a72add6c4d95',
    messagingSenderId: '791187601680',
    projectId: 'gauri-lab8-bf36b',
    storageBucket: 'gauri-lab8-bf36b.firebasestorage.app',
    iosBundleId: 'com.example.lab8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjdT2RFDlKLhFrQlB2puqTmdb5ni0H3Uo',
    appId: '1:791187601680:web:7a221af08fec15136c4d95',
    messagingSenderId: '791187601680',
    projectId: 'gauri-lab8-bf36b',
    authDomain: 'gauri-lab8-bf36b.firebaseapp.com',
    storageBucket: 'gauri-lab8-bf36b.firebasestorage.app',
    measurementId: 'G-NC7476WJWQ',
  );
}
